-- 2. Product Performance
-- How many products exist in each category? 
SELECT CAT_ID as Category ,COUNT(PROD_ID) as Total_products FROM PRODUCTS GROUP BY CAT_ID;

-- What is the average price of products by category? 
SELECT COUNT(PROD_ID), CAT_ID, AVG(PRICE) FROM PRODUCTS GROUP BY CAT_ID;

-- Which products have the highest total sales volume (by quantity)? 
SELECT P.PROD_ID,P.PROD_NAME, SUM(OD.QUANTITY) AS SALES_VOL_QUNATITY FROM PRODUCTS P
INNER JOIN ORDER_DETAILS OD ON
P.PROD_ID = OD.PROD_ID
GROUP BY PROD_ID
ORDER BY SALES_VOL_QUNATITY DESC
LIMIT 1;

-- What is the total revenue generated by each product? 
SELECT P.PROD_ID,P.PROD_NAME, SUM(PRICE) AS TOTAL_REVENUE FROM PRODUCTS P
INNER JOIN ORDER_DETAILS OD ON
P.PROD_ID = OD.PROD_ID
GROUP BY PROD_ID
ORDER BY TOTAL_REVENUE;

-- How do product sales vary by category and supplier? 
SELECT c.cat_name,s.sup_name,SUM(od.total_price) AS TotalSales
FROM order_details od
JOIN products p ON od.prod_id = p.prod_id
JOIN categories c ON p.cat_id = c.cat_id
JOIN supplier s ON p.sup_id = s.sup_id
GROUP BY c.cat_name, s.sup_name
ORDER BY TotalSales DESC;
    